jobs:
  full-test:
    container: cuaesd/aesd-autotest:assignment4-buildroot
    runs-on: self-hosted
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      # Add this step to download the missing linux-headers tarball
      - name: Download missing linux-headers
        run: |
          if [ ! -f /github/home/.dl/linux/linux-6.1.44.tar.xz ]; then
            curl -L -o /github/home/.dl/linux/linux-6.1.44.tar.xz https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.1.44.tar.xz
          fi

      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run full test
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        run: ./full-test.sh

      - name: Cleanup
        if: always()
        run: |
          ssh-add -D
