name: assignment-test
on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  full-test:
    container: cuaesd/aesd-autotest:assignment4-buildroot
    runs-on: self-hosted
    timeout-minutes: 180  # Increased from 120 to 180 minutes

    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # New step to install additional dependencies (if needed)
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y build-essential libtool autoconf

      # Enable verbose logging and handle build failure gracefully
      - name: Run full test
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        run: |
          ./full-test.sh --verbose || echo "Build failed, proceeding to cleanup"

      # Always run cleanup step
      - name: Cleanup
        if: always()
        run: |
          ssh-add -D
